version: "3.8"

services:
  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: netflix-clone
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
